### ISSUE TITLE
Party fight

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#133] opened 2023-02-12 15:14 UTC
when you play party fight's and it's more than 5 players it's bugged match never end

**Comment by GoodestEnglish** [comment] 2023-02-12 16:36
Need more details. For example, what type of match? How the bug exactly occurs? Any video  I can view?

**Comment by GoodestEnglish** [comment] 2023-02-12 18:04
Also, can someone try to replicate and reproduce this bug? Since I don't have 5 alts and my computer can't handle 5 minecraft instance 😅

**Comment by GoodestEnglish** [comment] 2023-02-27 11:45
Closing this as no more information

**Closed by GoodestEnglish** 2023-02-27 11:45 UTC
