### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#148] opened 2023-03-05 17:13 UTC
Map reset works broken. Sometimes just doesnt arena resets after match gone.
![image](https://user-images.githubusercontent.com/40424128/222975323-0ba7d3fc-0d1f-42c2-8116-a194868fb70b.png)

**Comment by Mekvil** [comment] 2023-03-05 17:17
error like https://github.com/diamond-rip/Eden/issues/91

**Comment by GoodestEnglish** [comment] 2023-03-05 20:47
That issue should be fixed ages ago. I've also tested with bots and ran thousand of matches and can't reproduce the error. However I will keep this for a while and see if anyone can reproduce this with more detailed information (for example: a method which can 100% reproduce the error)

**Comment by HierarchyMan** [comment] 2023-03-09 03:25
I think I know what happened I was kinda able to do it.
 So arenas won't reset if the server is shutdown while an ongoing game is being played
You could prolly fix this by doing what bedwars1058 does, it creates arena cache in a zip file as soon as the arena is saved so the server is protected even from hard resets

**Comment by GoodestEnglish** [comment] 2023-03-09 07:27
Makes sense. I will look into this.

**Comment by GoodestEnglish** [comment] 2023-03-12 21:31
Fixed in latest update. Now match arena will be restored when server stops.

**Closed by GoodestEnglish** 2023-03-12 21:31 UTC
Labels: question
