### ISSUE TITLE
Possible Knockback Bug 

### ISSUE THREAD

**Issue by Russhvith** [diamond-rip/Eden#220] opened 2023-03-26 15:51 UTC
So we are running CarbonSpigot as our server and although we set knockback profile in /kit menu and restarted, it does not seem to set the kit and player takes no kb from fishing rod or arrow(s). 

Just to verify, the kit is working properly and when we set it manually via /knockback set <Kb Profile> it works,
even the file is valid.

Is anyone else experiencing this issue? or is it a bug?

P.S resolve this soon,

Thanks,
Russhvith

**Comment by Prithu-K-Rai** [comment] 2023-03-26 16:13
Facing the same issue on my server. I had to use Imanity Spigot to fix it, but I prefer CarbonSpigot due to another  custom plugin that relies on it.

**Comment by GoodestEnglish** [comment] 2023-03-26 16:34
Confirmed this bug exists. Will be fixed in next version

**Comment by GoodestEnglish** [comment] 2023-03-26 17:00
Fixed in latest version

**Closed by GoodestEnglish** 2023-03-26 17:00 UTC
Labels: bug
