### ISSUE TITLE
Arenas not reseting (CarbonSpigot)

### ISSUE THREAD

**Issue by Prithu-K-Rai** [diamond-rip/Eden#224] opened 2023-03-28 17:19 UTC
For some reason, arenas refuse to reset:
![image](https://user-images.githubusercontent.com/95639926/228318605-ee3469a3-35e1-47a4-97dc-ed1cbbd4a52c.png)

**Comment by TehJays** [comment] 2023-03-28 18:20
Don't think its about the Spigot you're using, but I think its about the world the arena is in. I've had this error as well but moving it a new world might help.

**Comment by GoodestEnglish** [comment] 2023-03-29 05:04
Can't reproduce this bug. What is your min and max looks like? And is it occurs everytime?

**Comment by GoodestEnglish** [comment] 2023-03-29 05:18
> Don't think its about the Spigot you're using, but I think its about the world the arena is in. I've had this error as well but moving it a new world might help.

World shouldn't matter. Do you still have this error in the latest version?

**Comment by Prithu-K-Rai** [comment] 2023-03-29 10:40
> Can't reproduce this bug. What is your min and max looks like? And is it occurs everytime?

Occurs in main arenas, min and max are fine.

**Comment by GoodestEnglish** [comment] 2023-03-29 21:43
I am not familiar with SlimeWorldManager, so I am not sure. But from what I see from their source, it looks like they've modified some of the code which related to NMS chunk. And Eden uses NMS chunk to cache and reset arenas. This might be an issue but I am unsure.

Could you please test it again without SlimeWorldManager?

**Closed** 2023-04-10 08:58 UTC
Labels: question
